# Generated by Django 3.1.6 on 2021-05-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('content', models.URLField(max_length=1024)),
                ('description', models.TextField()),
                ('watched', models.IntegerField()),
                ('published', models.DateField(auto_now_add=True)),
                ('platfor', models.CharField(blank=True, max_length=254, null=True)),
                ('my_list_section', models.BooleanField(default=False)),
                ('new_video', models.BooleanField(default=False)),
                ('by_anatomy', models.BooleanField(default=False)),
                ('by_diseases', models.BooleanField(default=False)),
                ('by_subjects', models.BooleanField(default=False)),
                ('by_projects', models.BooleanField(default=False)),
                ('welcoming', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.category')),
            ],
        ),
    ]
