# Generated by Django 3.1.6 on 2021-05-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='platfor',
            new_name='platform',
        ),
        migrations.AlterField(
            model_name='videos',
            name='watched',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
