# Generated by Django 3.1.6 on 2021-05-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210507_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='src',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
