# Generated by Django 3.1.6 on 2021-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_category_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='src',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
