# Generated by Django 3.1.6 on 2021-05-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20210510_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='by_anatomy',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='by_diseases',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='by_projects',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='by_subjects',
        ),
    ]
