# Generated by Django 3.1.6 on 2021-05-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20210510_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.subjects'),
        ),
    ]
