# Generated by Django 3.1.6 on 2021-05-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_category_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subjects',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.subjects'),
        ),
    ]
