# Generated by Django 3.1.6 on 2021-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20210511_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='src',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
