# Generated by Django 3.1.6 on 2022-11-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_mylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='video',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='MyList',
        ),
    ]
