# Generated by Django 3.1.6 on 2022-11-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_auto_20221105_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='name',
        ),
    ]
