# Generated by Django 3.1.6 on 2022-11-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_auto_20221105_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mylist',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
