# Generated by Django 3.1.6 on 2022-11-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_auto_20221105_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
