# Generated by Django 3.1.6 on 2021-06-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20210602_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('saving', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.cards'),
        ),
    ]
