# Generated by Django 3.1.6 on 2021-07-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_cards_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='curency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='cards',
            name='description',
            field=models.CharField(default='Description', max_length=100),
        ),
    ]
