# Generated by Django 3.1.6 on 2021-07-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_auto_20210727_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='curency',
            field=models.CharField(blank=True, default='EUR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cards',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
