# Generated by Django 3.1.6 on 2021-07-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20210727_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='curency',
            new_name='currency',
        ),
        migrations.AddField(
            model_name='cards',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
