# Generated by Django 3.1.6 on 2021-08-01 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_auto_20210727_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
