# Generated by Django 3.1.6 on 2021-08-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20210801_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='town_or_city',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
