# Generated by Django 3.1.6 on 2021-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_auto_20210810_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
