# Generated by Django 3.1.6 on 2021-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_auto_20210810_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_number',
            field=models.CharField(max_length=32),
        ),
    ]
