# Generated by Django 3.1.6 on 2021-09-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
