# Generated by Django 3.1.6 on 2021-09-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_auto_20210911_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
