# Generated by Django 3.1.6 on 2022-11-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersprofile', '0002_auto_20221104_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('icon', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('icon', models.CharField(max_length=254)),
                ('slider_id', models.CharField(max_length=254)),
            ],
        ),
    ]
