# Generated by Django 3.1.6 on 2022-11-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0003_profilecategories_profilelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelinks',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersprofile.profilecategories'),
        ),
    ]
