# Generated by Django 3.1.6 on 2022-11-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0004_profilelinks_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelinks',
            name='slider_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
