# Generated by Django 3.1.6 on 2022-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0006_auto_20221104_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelinks',
            name='page_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
