# Generated by Django 3.1.6 on 2022-11-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0007_profilelinks_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilelinks',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProfileCategories',
        ),
        migrations.DeleteModel(
            name='ProfileLinks',
        ),
    ]
