# Generated by Django 3.1.6 on 2022-11-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0009_action_profilecategories_profilelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='profilelinks',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersprofile.profilecategories'),
        ),
    ]
