# Generated by Django 3.1.6 on 2022-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0011_auto_20221105_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelinks',
            name='action',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
