# Generated by Django 3.1.6 on 2022-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0013_remove_profilelinks_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelinks',
            name='show_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
