# Generated by Django 3.1.6 on 2022-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0014_profilelinks_show_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelinks',
            name='slider_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
